#!/bin/bash
# ============================================================
# AgentCEO — Weekly Summary
# Compiles the last 7 days of agent logs into a backer digest.
# Optionally sends via Telegram.
#
# Usage:
#   bash weekly_summary.sh agentname
#   bash weekly_summary.sh agentname --telegram
#   bash weekly_summary.sh agentname --output /path/to/file.md
# ============================================================

BASE_DIR="${AGENTCEO_BASE:-$HOME}"
AGENT_ARG=""
SEND_TELEGRAM=false
OUTPUT_FILE=""

for arg in "$@"; do
    case "$arg" in
        --telegram) SEND_TELEGRAM=true ;;
        --output)   shift; OUTPUT_FILE="$1" ;;
        -*)         echo "Unknown flag: $arg"; exit 1 ;;
        *)          AGENT_ARG="$arg" ;;
    esac
done

if [[ -z "$AGENT_ARG" ]]; then
    echo "Usage: bash weekly_summary.sh agentname [--telegram] [--output file.md]"
    exit 1
fi

# Resolve agent directory
if [[ "$AGENT_ARG" == /* ]] && [[ -d "$AGENT_ARG" ]]; then
    AGENT_DIR="$AGENT_ARG"
elif [[ -d "$BASE_DIR/$AGENT_ARG" ]]; then
    AGENT_DIR="$BASE_DIR/$AGENT_ARG"
else
    echo "❌ Agent '$AGENT_ARG' not found under $BASE_DIR"
    exit 1
fi

AGENT_NAME=$(basename "$AGENT_DIR")
CORE_MD="$AGENT_DIR/memory/core.md"
LOGS_DIR="$AGENT_DIR/logs"
TODAY=$(date '+%Y-%m-%d')
WEEK_START=$(date -d '7 days ago' '+%Y-%m-%d' 2>/dev/null || date -v-7d '+%Y-%m-%d')

# ── Load env ──────────────────────────────────────────────────────────────────
if [[ -f "$AGENT_DIR/.env" ]]; then
    set -a; source "$AGENT_DIR/.env" 2>/dev/null; set +a
fi

# ── Read core state ───────────────────────────────────────────────────────────
company=$(grep '- Company:' "$CORE_MD" 2>/dev/null | head -1 | sed 's/.*: //')
revenue=$(grep '- Current revenue:' "$CORE_MD" 2>/dev/null | head -1 | sed 's/.*: //')
status=$(grep '- Status:' "$CORE_MD" 2>/dev/null | head -1 | sed 's/.*: //')

# ── Collect last 7 log files ──────────────────────────────────────────────────
log_files=()
for log in "$LOGS_DIR"/*.md; do
    [[ -f "$log" ]] || continue
    log_date=$(basename "$log" .md)
    [[ "$log_date" < "$WEEK_START" ]] && continue
    [[ "$log_date" > "$TODAY" ]] && continue
    log_files+=("$log")
done

# Sort newest first
IFS=$'\n' log_files=($(sort -r <<< "${log_files[*]}")); unset IFS

# ── Extract bullet points from logs ──────────────────────────────────────────
all_tasks=""
days_active=0
for log in "${log_files[@]}"; do
    log_date=$(basename "$log" .md)
    day_tasks=$(grep '^- ' "$log" 2>/dev/null | grep -v '^- $' | head -10)
    if [[ -n "$day_tasks" ]]; then
        all_tasks+="**$log_date**"$'\n'"$day_tasks"$'\n\n'
        (( days_active++ ))
    fi
done

task_count=$(grep -c '^- ' "$LOGS_DIR"/*.md 2>/dev/null | awk -F: 'NR<=7{sum+=$2}END{print sum}')

# ── Build report ──────────────────────────────────────────────────────────────
build_report() {
    echo "# $AGENT_NAME — Weekly Summary"
    echo "_$WEEK_START to $TODAY_"
    echo ""
    echo "## At a Glance"
    echo "- **Company:** ${company:-—}"
    echo "- **Status:** ${status:-Active}"
    echo "- **Revenue:** ${revenue:-\$0}"
    echo "- **Days active:** $days_active / 7"
    echo "- **Tasks logged:** ${task_count:-0}"
    echo ""
    if [[ -n "$all_tasks" ]]; then
        echo "## Activity Log"
        echo "$all_tasks"
    else
        echo "_No log entries found for this week._"
        echo ""
    fi
    echo "---"
    echo "_Generated by AgentCEO weekly_summary.sh · $TODAY_"
}

REPORT=$(build_report)

# ── Output ────────────────────────────────────────────────────────────────────
if [[ -n "$OUTPUT_FILE" ]]; then
    echo "$REPORT" > "$OUTPUT_FILE"
    echo "✅ Summary written to $OUTPUT_FILE"
else
    echo "$REPORT"
fi

# ── Telegram ──────────────────────────────────────────────────────────────────
if [[ "$SEND_TELEGRAM" == true ]]; then
    NOTIFY_SCRIPT="$(dirname "${BASH_SOURCE[0]}")/telegram_notify.sh"
    if [[ ! -f "$NOTIFY_SCRIPT" ]]; then
        NOTIFY_SCRIPT="$AGENT_DIR/scripts/telegram_notify.sh"
    fi
    if [[ -f "$NOTIFY_SCRIPT" ]]; then
        # Send a condensed version
        short="📋 *$AGENT_NAME — Weekly Summary*
_$WEEK_START to $TODAY_

📊 Status: ${status:-Active}
💰 Revenue: ${revenue:-\$0}
📅 Days active: $days_active/7
✅ Tasks logged: ${task_count:-0}

_Full report saved to $AGENT_DIR/logs/weekly_$TODAY.md_"
        AGENT_DIR="$AGENT_DIR" bash "$NOTIFY_SCRIPT" "$short"
    else
        echo "⚠️  telegram_notify.sh not found — skipping Telegram send"
    fi
    # Always save full report to logs
    echo "$REPORT" > "$AGENT_DIR/logs/weekly_$TODAY.md"
    echo "✅ Full report saved to $AGENT_DIR/logs/weekly_$TODAY.md"
fi
